/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    id("org.springframework.boot") version "2.7.4"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://repo1.maven.org/maven2")
    }

    maven {
        url = uri("https://akeyless.jfrog.io/artifactory")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-actuator:2.7.4")
    implementation("org.springframework.boot:spring-boot-starter-data-rest:2.7.4")
    implementation("org.springframework.boot:spring-boot-starter-web:2.7.4")
    implementation("org.projectlombok:lombok:1.18.24")
    implementation("io.akeyless:akeyless-java:2.19.0")
    runtimeOnly("org.springframework.boot:spring-boot-devtools:2.7.4")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.4")
}

group = "io.akeyless.examples"
version = "0.0.1-SNAPSHOT"
description = "example-sdk-encryption-as-a-service"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
